#!/bin/sh
bspc rule -r "*"

###---Autostart---###
# Set keyboard layout
setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
# Run hotkeys daemon
pgrep -x sxhkd > /dev/null || sxhkd &
# Network manager applet
nm-applet &
# Load Xresources
xrdb ~/.Xresources &
# Load wallpaper
feh --bg-scale /mnt/storage/Pictures/Wallpapers/more\ landscape.jpg
# Load screen compositor
picom -b --config /home/pablo/.config/picom/picom.conf
# Load notification daemon
dunst &
# Load polybar
~/.config/polybar/launch.sh &
# Redshift (bluelight filter)
redshift

export _JAVA_AWT_WM_NONREPARENTING=1

###---MONITORS---###
bspc monitor -d Browser Code Terminal Chat Keys Misc Music

###---Global Settings---###
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#FFFFFF"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 30
bspc config bottom_padding 10
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 3
bspc config window_gap 10

###---Rules---###
bspc rule -a firefox desktop=^1
bspc rule -a Slack desktop=^4
bspc rule -a KeePassXC desktop=^5



