#!/bin/sh
bspc rule -r "*"

###---Autostart---###
pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
xrdb ~/.Xresources &
feh --bg-scale /mnt/storage/Pictures/Wallpapers/more\ landscape.jpg
picom -b --config /home/pablo/.config/picom/picom.conf
dunst &
~/.config/polybar/launch.sh &

export _JAVA_AWT_WM_NONREPARENTING=1

###---MONITORS---###
bspc monitor -d Browser Code Terminal Chat Keys Misc Music

###---Global Settings---###
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 30
bspc config bottom_padding 10
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above

