;; --------------------------------------
;;       ____      _                
;;      / ___|___ | | ___  _ __ ___ 
;;     | |   / _ \| |/ _ \| '__/ __|
;;     | |__| (_) | | (_) | |  \__ \
;;      \____\___/|_|\___/|_|  |___/
;; --------------------------------------

[colors]

;; Main colors
bg = #99444444
bg-alt = #99333333
fg = #FFFFFF
fg-alt = #66AFAFAF
ul = #FFFFFF
alert = #0000FF

