;; --------------------------------------
;;       ____      _                
;;      / ___|___ | | ___  _ __ ___ 
;;     | |   / _ \| |/ _ \| '__/ __|
;;     | |__| (_) | | (_) | |  \__ \
;;      \____\___/|_|\___/|_|  |___/
;; --------------------------------------

[colors]

;; Main colors
bg = #CC444444
bg-alt = #99333333
fg = #FFFFFF
fg-alt = #66AFAFAF
ul = #FFFFFF
alert = #ec2e2e

;;
red = #ec2e2e
orange = #ec732e
yellow = #f7f43f
green = #33e138

