;; --------------------------------------
;;       ____      _                
;;      / ___|___ | | ___  _ __ ___ 
;;     | |   / _ \| |/ _ \| '__/ __|
;;     | |__| (_) | | (_) | |  \__ \
;;      \____\___/|_|\___/|_|  |___/
;; --------------------------------------

[colors]

;; Main colors
bg = #336699
bg-alt = #6699CC
fg = #333333
fg-alt = #666666
ul = #3333FF

alert = #0000FF

