;; --------------------------------------
;;       _____           _       
;;      |  ___|__  _ __ | |_ ___ 
;;      | |_ / _ \| '_ \| __/ __|
;;      |  _| (_) | | | | |_\__ \
;;      |_|  \___/|_| |_|\__|___/
;; --------------------------------------

[fonts]

main = "Hack Nerd Font:size=10;2"
main-alt = ""
icons = "Hack Nerd Font:size=11;3"
icons-alt = ""

