[icons]
calendar = 
clock = 

;; Weather
clear-day = 
wind-day = 
rain-day = 
storm-day =  
clear-night =  
wind-night = 
rain-night = 
storm-night = 
mist = 

;; Bluetooth
bt = 
bt-off = 
bt-connected = 
bt-scanning = 

;; Apps
firefox = 
arch = 

;; Mail
mail-unread = 
mail-read = 

;; Network
lan = 
network = 
vpn = ﱱ
internet = 慎
wifi-on = 直
wifi-off = 睊

;; Volume
volume-low = 奄
volume-med = 奔
volume-hi = 墳
volume-mute = 婢

;; Battery
battery-5 = 
battery-4 = 
battery-3 = 
battery-2 = 
battery-1 = 
battery-charging-5 = 
battery-charging-4 = 
battery-charging-3 = 
battery-charging-2 = 
battery-charging-1 = 

;; Temp
temp-low = 
temp-med = 
temp-hi = 

;; Misc
music = ﱘ
brightness-high = ﯦ
brightness-low = ﯧ
code = 謹
cpu = 
chat = 
terminal = 
search = 
question = 
key = 
ram = 

